//ui.js
function ensureFontAwesome() {
    if (!document.querySelector('link[href*="font-awesome"]')) {
        const link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css';
        link.crossOrigin = 'anonymous';
        link.referrerPolicy = 'no-referrer';
        document.head.appendChild(link);
    }
}

function createLoadingState() {
    const container = document.createElement('div');
    container.id = 'page-summary-loading';
    
    const shadow = container.attachShadow({ mode: 'open' });
    
    const fontAwesome = document.createElement('link');
    fontAwesome.rel = 'stylesheet';
    fontAwesome.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css';
    
    const styles = document.createElement('link');
    styles.rel = 'stylesheet';
    styles.href = chrome.runtime.getURL('src/styles.css');
    
    const wrapper = document.createElement('div');
    wrapper.className = 'ob-body';  // Updated class name
    
    const spinner = document.createElement('div');
    spinner.className = 'ob-spinner';  // Updated class name
    
    const loadingText = document.createElement('span');
    loadingText.textContent = 'Generating page summary...';
    
    wrapper.appendChild(spinner);
    wrapper.appendChild(loadingText);
    
    shadow.appendChild(fontAwesome);
    shadow.appendChild(styles);
    shadow.appendChild(wrapper);
    
    return container;
}

function createShareButton(summaryData) {
    const button = document.createElement('button');
    button.className = 'ob-share-button';  // Updated from 'share-button' to 'ob-share-button'
    button.innerHTML = `
        <i class="fas fa-share-alt" style="font-size: 16px;"></i>
        Share Summary
    `;

    button.onclick = async () => {
        const shareText = `📝 Summary:\n${summaryData.summary}\n\n🎯 Key Takeaways:\n${summaryData.keyTakeaways.map(point => `• ${point}`).join('\n')}\n\n🔗 ${window.location.href}\n\n✨ Generated by Offbait\nGet the extension: https://offbait.io/install`;

        try {
            await navigator.clipboard.writeText(shareText);
            showCopiedMessage();
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    return button;
}

function createSummaryUI(summaryData) {
    const container = document.createElement('div');
    container.id = 'page-summary-extension';
    
    const shadow = container.attachShadow({ mode: 'open' });
    
    // Add Font Awesome
    const fontAwesome = document.createElement('link');
    fontAwesome.rel = 'stylesheet';
    fontAwesome.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css';
    
    // Add your existing styles
    const styles = document.createElement('link');
    styles.rel = 'stylesheet';
    styles.href = browser.runtime.getURL('src/styles.css');
    
    const wrapper = document.createElement('div');
    wrapper.className = 'ob-body';
    
    // Create header
    const header = createHeader();
    
    // Create close button
    const closeButton = createCloseButton(() => container.remove());
    
    // Create content elements
    const content = createContent(summaryData);
    
    // Create share button
    const shareButton = createShareButton(summaryData);
    
    // Assemble everything
    wrapper.appendChild(closeButton);
    wrapper.appendChild(header);
    Object.values(content).forEach(element => wrapper.appendChild(element));
    wrapper.appendChild(shareButton); // Make sure to append the share button
    
    shadow.appendChild(fontAwesome);
    shadow.appendChild(styles);
    shadow.appendChild(wrapper);
    
    return container;
}

function createHeader() {
    const header = document.createElement('div');
    header.style.cssText = `
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
        padding-bottom: 15px;
        border-bottom: 1px solid #eee;
    `;

    const logoText = document.createElement('div');
    logoText.textContent = '🪝 offbait';
    logoText.style.cssText = `
        font-size: 24px;
        font-weight: bold;
        display: flex;
        align-items: center;
        gap: 5px;
    `;

    const rightSection = document.createElement('div');
    rightSection.style.cssText = `
        display: flex;
        align-items: center;
        gap: 15px;
    `;

    const githubLink = document.createElement('a');
    githubLink.href = 'https://github.com/stoyan-stoyanov/offbait';
    githubLink.style.cssText = `
        color: #333;
        text-decoration: none;
        display: flex;
        align-items: center;
        gap: 5px;
        font-size: 14px;
    `;

    githubLink.innerHTML = `
        <i class="fab fa-github" style="font-size: 20px;"></i>
        GitHub
    `;
    githubLink.target = '_blank';


    rightSection.appendChild(githubLink);

    header.appendChild(logoText);
    header.appendChild(rightSection);

    return header;
}

function createCloseButton(onClose) {
    const closeButton = document.createElement('button');
    closeButton.innerHTML = '<i class="fas fa-times"></i>';
    closeButton.style.cssText = `
        position: absolute;
        right: 20px;
        top: 20px;
        border: none;
        background: none;
        cursor: pointer;
        font-size: 16px;
        color: #7f8c8d;
        padding: 5px;
    `;
    closeButton.onclick = onClose;
    return closeButton;
}

function createContent(summaryData) {
    const elements = {};

    // Article Title
    elements.title = document.createElement('h1');
    elements.title.textContent = summaryData.title;
    elements.title.style.cssText = `
        margin: 0 0 20px 0;
        font-size: 1.6em;
        color: #2c3e50;
        font-weight: 600;
    `;

    // Summary Section
    elements.summaryTitle = document.createElement('h2');
    elements.summaryTitle.textContent = '✨ Summary';
    elements.summaryTitle.style.cssText = `
        margin: 0 0 10px 0;
        font-size: 1.4em;
        color: #2c3e50;
    `;

    elements.summaryText = document.createElement('p');
    elements.summaryText.textContent = summaryData.summary;
    elements.summaryText.style.cssText = `
        margin: 0 0 20px 0;
        line-height: 1.5;
        color: #34495e;
    `;

    // Key Takeaways
    elements.takeawaysTitle = document.createElement('h3');
    elements.takeawaysTitle.textContent = '🎯 Key Takeaways';
    elements.takeawaysTitle.style.cssText = `
        margin: 0 0 10px 0;
        font-size: 1.2em;
        color: #2c3e50;
    `;

    elements.takeawaysList = document.createElement('ul');
    elements.takeawaysList.style.cssText = `
        margin: 0 0 20px 0;
        padding-left: 20px;
        line-height: 1.4;
        color: #34495e;
        list-style: disc;
    `;

    summaryData.keyTakeaways.forEach(takeaway => {
        const li = document.createElement('li');
        li.textContent = takeaway;
        li.style.marginBottom = '5px';
        elements.takeawaysList.appendChild(li);
    });

    return elements;
}

function showCopiedMessage() {
    const notification = document.createElement('div');
    notification.textContent = 'Copied to clipboard!';
    notification.style.cssText = `
        position: fixed;
        bottom: 20px;
        right: 20px;
        background: #2ecc71;
        color: white;
        padding: 10px 20px;
        border-radius: 5px;
        animation: fadeOut 2s forwards;
    `;
    document.body.appendChild(notification);
    setTimeout(() => notification.remove(), 2000);
}